/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tosri' at '3/12/17 6:26 PM' with Gradle 3.1
 *
 * @author tosri, @date 3/12/17 6:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
